changelog:
  categories:
    - title: New Features
      labels:
        - "new-feature"
    - title: Documentation
      labels:
        - "documentation"
    - title: Bugs fixed
      labels:
        - "bug"
    - title: Other Changes
      labels:
        - "*"
